// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RejectionTemplatesController from "./rejection_templates_controller"
application.register("rejection-templates", RejectionTemplatesController)

import RejectionReasonController from "./rejection_reason_controller"
application.register("rejection-reason", RejectionReasonController)

import MobileNavController from "./mobile_nav_controller"
application.register("mobile-nav", MobileNavController)
